from abc import ABC, abstractmethod


class BrowserBackend(ABC):
    @abstractmethod
    async def navigate(self, url: str, wait_until: str = "domcontentloaded") -> str: ...
    @abstractmethod
    async def click(self, selector: str, button: str = "left", timeout: int = 5000) -> str: ...
    @abstractmethod
    async def click_text(self, text: str, exact: bool = False) -> str: ...
    @abstractmethod
    async def type(self, selector: str, text: str, clear_first: bool = True, press_enter: bool = False) -> str: ...
    @abstractmethod
    async def select(self, selector: str, value: str) -> str: ...
    @abstractmethod
    async def hover(self, selector: str) -> str: ...
    @abstractmethod
    async def scroll(self, direction: str = "down", amount: int = 500) -> str: ...
    @abstractmethod
    async def extract(self, selector: str = "body", attribute: str = "innerText", multiple: bool = False) -> str: ...
    @abstractmethod
    async def extract_table(self, selector: str = "table") -> str: ...
    @abstractmethod
    async def extract_links(self) -> str: ...
    @abstractmethod
    async def execute_js(self, script: str) -> str: ...
    @abstractmethod
    async def screenshot(
        self, output_path: str | None = None, full_page: bool = False, selector: str | None = None
    ) -> str: ...
    @abstractmethod
    async def fill_form(self, fields: dict[str, str], submit_selector: str | None = None) -> str: ...
    @abstractmethod
    async def new_tab(self, url: str | None = None) -> str: ...
    @abstractmethod
    async def close_tab(self, tab_index: int = -1) -> str: ...
    @abstractmethod
    async def list_tabs(self) -> str: ...
    @abstractmethod
    async def switch_tab(self, tab_index: int) -> str: ...
    @abstractmethod
    async def back(self) -> str: ...
    @abstractmethod
    async def forward(self) -> str: ...
    @abstractmethod
    async def refresh(self) -> str: ...
    @abstractmethod
    async def wait(self, selector: str | None = None, timeout: int = 10000, state: str = "visible") -> str: ...
    @abstractmethod
    async def close(self) -> str: ...
    @abstractmethod
    async def get_page_info(self) -> str: ...
