"""Task Decomposition Engine — breaks complex goals into executable subtasks.

Complex user requests are decomposed into a tree of subtasks, each with
dependencies, estimated complexity, and the assigned agent.

Example:
  User: "Build a Flask API for todo list"
  →  1. create_project_folder       (system)
     2. install_flask              (system, depends_on=[1])
     3. generate_api_code          (code, depends_on=[1])
     4. create_requirements_txt    (code, depends_on=[2])
     5. run_tests                  (code, depends_on=[3,4])

The decomposition is generated by the LLM planner, but this module
provides the structural framework, dependency resolution, and
execution ordering via topological sort.
"""

from __future__ import annotations

import json
import logging
import uuid
from dataclasses import dataclass, field
from enum import StrEnum
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pilot.models.router import ModelRouter

from pilot.utils.logger import get_logger

logger = get_logger( "pilot.agents.decomposer")


class SubtaskStatus(StrEnum):
    PENDING = "pending"
    READY = "ready"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"
    SKIPPED = "skipped"


@dataclass
class Subtask:
    """A single subtask in a decomposed goal."""

    id: str = field(default_factory=lambda: str(uuid.uuid4().hex)[:8])
    title: str = ""
    description: str = ""
    agent: str = "system"
    depends_on: list[str] = field(default_factory=list)
    status: SubtaskStatus = SubtaskStatus.PENDING
    estimated_complexity: float = 0.5  # 0.0 = trivial, 1.0 = very complex
    output: str = ""
    error: str = ""
    order: int = 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "title": self.title,
            "description": self.description,
            "agent": self.agent,
            "depends_on": self.depends_on,
            "status": self.status.value,
            "estimated_complexity": self.estimated_complexity,
            "output": self.output,
            "error": self.error,
            "order": self.order,
        }


@dataclass
class TaskDecomposition:
    """A full decomposition of a complex goal into subtasks."""

    goal: str = ""
    subtasks: list[Subtask] = field(default_factory=list)
    is_complex: bool = False
    estimated_total_time: str = ""
    decomposition_id: str = field(default_factory=lambda: str(uuid.uuid4().hex)[:8])

    def to_dict(self) -> dict[str, Any]:
        return {
            "decomposition_id": self.decomposition_id,
            "goal": self.goal,
            "is_complex": self.is_complex,
            "estimated_total_time": self.estimated_total_time,
            "subtask_count": len(self.subtasks),
            "subtasks": [s.to_dict() for s in self.subtasks],
        }


DECOMPOSITION_PROMPT = """\
You are a task decomposition engine for an AI agent called Heliox OS.
Given a user goal, determine if it requires multiple steps and break it down.

User Goal: {goal}

If simple (1-2 actions), respond:
{{"is_complex": false, "subtasks": []}}

If complex (3+ actions), decompose into ordered subtasks. Each subtask has:
- title: short name
- description: what to do
- agent: which specialist handles it (system, code, web, monitor, communication)
- depends_on: list of subtask IDs this depends on (use indices like "0","1","2")
- estimated_complexity: 0.0 to 1.0

Respond with ONLY valid JSON:
{{
  "is_complex": true,
  "estimated_total_time": "30s",
  "subtasks": [
    {{"title": "...", "description": "...", "agent": "system", "depends_on": [], "estimated_complexity": 0.3}},
    {{"title": "...", "description": "...", "agent": "code", "depends_on": ["0"], "estimated_complexity": 0.6}}
  ]
}}
"""


class TaskDecomposer:
    """Decomposes complex goals into ordered, dependency-aware subtasks."""

    def __init__(self, model_router: ModelRouter) -> None:
        self._model = model_router

    async def decompose(self, goal: str) -> TaskDecomposition:
        """Analyze a goal and decompose it into subtasks if complex."""
        decomposition = TaskDecomposition(goal=goal)

        try:
            prompt = DECOMPOSITION_PROMPT.format(goal=goal)
            response = await self._model.generate(prompt)
            data = json.loads(response)

            decomposition.is_complex = data.get("is_complex", False)
            decomposition.estimated_total_time = data.get("estimated_total_time", "")

            for i, st in enumerate(data.get("subtasks", [])):
                subtask = Subtask(
                    title=st.get("title", f"Step {i + 1}"),
                    description=st.get("description", ""),
                    agent=st.get("agent", "system"),
                    depends_on=st.get("depends_on", []),
                    estimated_complexity=st.get("estimated_complexity", 0.5),
                    order=i,
                )
                decomposition.subtasks.append(subtask)

        except Exception:
            logger.debug("LLM decomposition failed, treating as simple", exc_info=True)
            decomposition.is_complex = False

        return decomposition

    def get_execution_order(self, decomposition: TaskDecomposition) -> list[list[Subtask]]:
        """Topological sort — returns batches of subtasks that can run in parallel.

        Each batch contains subtasks whose dependencies are all satisfied.
        """
        if not decomposition.subtasks:
            return []

        # Build adjacency by order index
        id_map = {str(i): st for i, st in enumerate(decomposition.subtasks)}
        id_map.update({st.id: st for st in decomposition.subtasks})

        completed: set[str] = set()
        remaining = list(decomposition.subtasks)
        batches: list[list[Subtask]] = []

        max_iterations = len(remaining) + 1
        for _ in range(max_iterations):
            if not remaining:
                break

            # Find all subtasks whose deps are satisfied
            ready = [st for st in remaining if all(dep in completed for dep in st.depends_on)]

            if not ready:
                # Break deadlock — force remaining into batch
                ready = list(remaining)

            batches.append(ready)
            for st in ready:
                completed.add(str(st.order))
                completed.add(st.id)
            remaining = [st for st in remaining if st not in ready]

        return batches

    def get_summary(self, decomposition: TaskDecomposition) -> str:
        """Human-readable decomposition summary."""
        if not decomposition.is_complex:
            return f"Simple task: {decomposition.goal}"

        lines = [
            f"📋 Task Decomposition: {decomposition.goal}",
            f"   Subtasks: {len(decomposition.subtasks)}",
            f"   Est. Time: {decomposition.estimated_total_time}",
            "",
        ]
        for i, st in enumerate(decomposition.subtasks):
            dep_str = f" (after: {', '.join(st.depends_on)})" if st.depends_on else ""
            lines.append(f"   {i + 1}. [{st.agent}] {st.title}{dep_str}")

        return "\n".join(lines)
